# Generated by Django 4.2.3 on 2023-07-24 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fullname', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female'), ('Other', 'Other')], default='Other', max_length=100)),
                ('contactnumber', models.IntegerField()),
                ('address', models.CharField(max_length=1000)),
                ('medicalcondition', models.CharField(max_length=1000)),
            ],
        ),
    ]
