# Generated by Django 4.2.3 on 2023-07-25 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='Fullname',
            new_name='fullname',
        ),
        migrations.AddField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(default='NULL', upload_to='profile_pictures'),
        ),
    ]
