# Generated by Django 4.2.3 on 2023-07-25 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0002_rename_fullname_patients_fullname_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='medicalcondition',
            new_name='Medical_Condition',
        ),
        migrations.RenameField(
            model_name='patients',
            old_name='contactnumber',
            new_name='contact_number',
        ),
    ]
