# Generated by Django 4.2.3 on 2023-07-25 13:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_rename_medicalcondition_patients_medical_condition_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='patients',
            old_name='Medical_Condition',
            new_name='medical_condition',
        ),
    ]
