# Generated by Django 4.2.3 on 2023-07-25 14:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_rename_medical_condition_patients_medical_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pictures'),
        ),
    ]
