# Generated by Django 4.2.3 on 2023-07-25 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_alter_patients_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(default='https://cdn-icons-png.flaticon.com/512/3135/3135715.png', upload_to='profile_pictures'),
        ),
    ]
