# Generated by Django 4.2.3 on 2023-07-25 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0006_alter_patients_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(default='NULL', upload_to='profile_pictures'),
        ),
    ]
