# Generated by Django 4.2.3 on 2023-07-25 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0009_alter_patients_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patients',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='profile_pictures'),
        ),
    ]
